### ISSUE TITLE
订阅yaml格式的文件会失败

### ISSUE THREAD

**Issue by EndOfMaster** [yanue/V2rayU#1203]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```

请预览一下你填的内容再提交。
1. v2rayU: 3.3.0, mac: 13.3.1 (22E261)
2. 订阅yaml格式的文件会失败，程序会卡死，强制关闭或者重装软件或者重启电脑都无效
3. 附上导入文件格式（备注：文件有198k）
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:
- name: 🇳🇱 荷兰-专线
  type: vmess
  server: xxxxxxxx
  port: '443'
  uuid: xxxxxxxxxxx
  alterId: '0'
  cipher: auto
  udp: true
  network: ws
  ws-path: f13fc07b2bc6
  ws-headers:
    Host: xxxxxxx
  ws-opts:
    path: f13fc07b2bc6
    headers:
      Host: xxxxxxxx
  tls: true
```
